version: '3'
services:
  aceleradev-postgres:
    image: "postgres:latest"
    container_name: "mystore-postgres"
    environment:
      - POSTGRES_DB=mystore_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - "5432:5432"